kind: pipeline
type: docker
name: application
steps:
  - name: staging-deployment
    image: docker:git
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      DOCKER_REGISTRY_USER:
        from_secret: DOCKER_REGISTRY_USER
      DOCKER_REGISTRY_PASSWORD:
        from_secret: DOCKER_REGISTRY_PASSWORD
      SERVER_ADDRESS:
        from_secret: SERVER_ADDRESS
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
      SSH_KNOWN_HOSTS:
        from_secret: SSH_KNOWN_HOSTS
      SERVER_USER:
        from_secret: SERVER_USER

    commands:
      - sleep 5 # just to let docker to be ready
      - echo "Configuring the ssh"

      ## Install ssh-agent if not already installed, it's required by docker.
      - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

      ## Run ssh-agent inside the docker container
      - eval "$(ssh-agent -s)"

      ## Add the ssh private key variable to the agent store.
      ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - >/dev/null

      ## Create the ssh directory and give it the right permissions
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh

      ## Configuring the ssh known hosts and gibe it the right permissions
      - echo "$SSH_KNOWN_HOSTS" >~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts

      - cd server && bin/build.sh && bin/deploy.sh

trigger:
  branch:
    - feature/new-new-colloc
  event:
    - push

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock